### ISSUE TITLE
TypeError: Use async with instead  - error while using aiohttp 3.3.2

### ISSUE THREAD

**Issue by divyanshu16** [aio-libs/aiohttp-cors#184]
While using asyncio and aiohttp, I am getting this error  on environment: Python 3, mac
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/divyanshushekhar/ScrapeFOLDER/Scraping/scrape-parallel.py", line 173, in <module>
    with aiohttp.ClientSession(loop=loop) as session:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/client.py", line 806, in __enter__
    raise TypeError("Use async with instead")
TypeError: Use async with instead
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x111337b38>
```

Searching google gives the result https://stackoverflow.com/questions/46066629/proxy-broker-error-use-async-with-instead which says to install aiohttp version 2.0.0 which I did but got another issue https://github.com/aio-libs/aiohttp-cors/issues/183

**Comment by likewhoa** [comment]
Happening here with aiohttp-3.4.4 as well

**Comment by asvetlov** [comment]
```
  File "/Users/divyanshushekhar/ScrapeFOLDER/Scraping/scrape-parallel.py", line 173, in <module>
    with aiohttp.ClientSession(loop=loop) as session:
```
replace 
`with aiohttp.ClientSession(loop=loop) as session:` 
to 
`async with aiohttp.ClientSession(loop=loop) as session:`
