### ISSUE TITLE
can not use  when  aiohttp version > v1.0.5

### ISSUE THREAD

**Issue by zhaoyihong** [aio-libs/aiohttp-cors#56]
[E 2016-11-18_11:45:00 server:208]
Traceback (most recent call last):
  File "/Users/yihong/virtualenvs/py35/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/Users/yihong/virtualenvs/py35/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
    resp = yield from handler(request)
  File "/Users/yihong/virtualenvs/py35/lib/python3.5/site-packages/aiohttp_cors/cors_config.py", line 253, in _preflight_handler
    request, origin, request_method)
  File "/Users/yihong/virtualenvs/py35/lib/python3.5/site-packages/aiohttp_cors/urldispatcher_router_adapter.py", line 400, in get_preflight_request_config
    requested_method, path)
TypeError: resolve() takes 2 positional arguments but 3 were given

can somebody update it?

**Comment by asvetlov** [comment]
Fixed by aiohttp-cors 0.5.0 release
